version: '3.5'

services:
  postgres:
    container_name: craftup_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: craftup_dev
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "1231:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: craftup_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "1232:80"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: craftup_api
    build: ./backend
    ports:
      - "1233:${API_PORT}"
    environment:
      PORT: ${API_PORT}
      MIX_ENV: staging
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
